version: "3"

services:
  web:
    restart: always
    build: .
    image: ghcr.io/atsu1125/groundpolis:latest
    links:
      - db
      - redis
#      - es
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - internal_network
      - external_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/info || exit 0"]
    volumes:
      - ./.config/dockerdefault.yml:/misskey/.config/default.yml

      - ./files:/misskey/files

  redis:
    restart: always
    image: redis:alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:14.1-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "example-misskey-user", "-d", "groundpolis"]
    env_file:
      - .config/docker_example.env
    volumes:
      - ./db:/var/lib/postgresql/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  external_network:
