name: Node.js CI
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      postgres:
        image: postgres:12.2-alpine
        ports:
          - 54355:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:4.0-alpine
        ports:
          - 56312:6379

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3.0.0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Enable corepack
      run: corepack enable
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Copy Configure
      run: cp test/test.yml .config
    - name: Build
      run: pnpm build
    - name: Check webpack process
      run: ls built/meta.json
    - name: Test
      run: pnpm test
